

package stringplay;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import javax.swing.*;
import java.io.*;
public class SettingsFrame extends javax.swing.JFrame {
    private File setting = new File("C:\\String Play Settings.ini");
    private String settings="";
    static SingleFrameApplication app;

    public SettingsFrame(SingleFrameApplication parent) {
        app=parent;
        initComponents();
        setVisible(true);
    }

    private class SaveFileTask extends StringPlayApp.SaveFileTask {
        SaveFileTask(File file) {
            super(app, file,settings);
        }

        @Override protected void succeeded(Void ignored) {
            
        }

        @Override protected void failed(Throwable e) {
            String msg = "File Saving error has occured.";
            String title = "Saving Error";
            int type = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(app.getMainFrame(), msg, title, type);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("StringPlay - Settings");
        setAlwaysOnTop(true);

        jLabel1.setText("The settings .ini file could not be found or is moved. A new settings file will be created in C: directory.");

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(stringplay.StringPlayApp.class).getContext().getActionMap(SettingsFrame.class, this);
        jButton1.setAction(actionMap.get("Okay")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton1)
                .add(38, 38, 38))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    @Action
    public void Okay() {
        settings="SkinBGR=255"+
                "\nSkinBGG=255"+
                "\nSkinBGB=255"+
                "\nSkinFGR=0"+
                "\nSkinFGG=0"+
                "\nSkinFGB=0"+
                "\nAppLastPath=C:\\"+
                "\nSkin#=5"+
                "\nAppEncrypt=1";
        try { BufferedWriter out = new BufferedWriter(new FileWriter(setting));
        out.write(settings);
        out.close(); }catch (IOException e) { }
        setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
